version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:13-3.1-alpine
    networks:
      - directus
    environment:
      POSTGRES_DB: 'directus'
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'd1r3ctu5'

  cache:
    container_name: cache
    image: redis:6.2.5-alpine
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '743bb977-c47e-452f-ba93-c7d4660319b9'
      SECRET: 'bELHYZxCz2aUHCRcG2qCGZWqjrQp8DCe'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'd1r3ctu5'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

networks:
  directus:
